### ISSUE TITLE
requirements missing keras

### ISSUE THREAD

**Issue by QingzhiHu** [dfdazac/blp#5] opened 2022-01-19 21:42 UTC
Error: "ModuleNotFoundError: No module named 'keras.api'"
After pip install keras==2.6.0. this problem is resolved.

**Comment by QingzhiHu** [comment] 2022-01-19 21:42
https://github.com/keras-team/keras/issues/15175

**Comment by dfdazac** [comment] 2022-01-21 14:49
Thanks for pointing this out. What script did you try to run before getting this error?

**Comment by QingzhiHu** [comment] 2022-01-21 14:52
I remember its utils.py under the root directory (as I mistook it for it being utils.py inside of data folder at the beginning).

**Comment by dfdazac** [comment] 2022-04-28 11:57
Since I couldn't reproduce this issue, and Keras is not used in our project, I will close this issue for now. I can investigate further if the issue persists.

**Closed as completed by dfdazac** 2022-04-28 11:57 UTC
